import 'package:db_viewer/features/database/models/database_schema.dart';
import 'package:db_viewer/features/database/services/postgres_database.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  test('schema discovery includes all PostgreSQL relation types', () {
    final sql = PostgresDatabase.schemaRelationsSql;

    expect(sql, contains("'r'"));
    expect(sql, contains("'p'"));
    expect(sql, contains("'v'"));
    expect(sql, contains("'m'"));
    expect(sql, contains("'f'"));
    expect(sql, contains('ORDER BY c.relname'));
  });

  test('table DDL includes constraints, foreign keys, indexes and triggers', () {
    final ddl = PostgresDatabase.buildTableDdl(
      schema: 'sales',
      table: 'orders',
      relationType: 'Table',
      owner: 'app_user',
      comment: "Customer's orders",
      tablespace: 'pg_default',
      persistence: 'Permanent',
      viewDefinition: '',
      columns: const [
        DatabaseColumn(
          name: 'id',
          dataType: 'bigint',
          nullable: false,
          primaryKey: true,
          identity: 'BY DEFAULT',
          comment: 'Order identifier',
        ),
        DatabaseColumn(
          name: 'customer_id',
          dataType: 'bigint',
          nullable: false,
        ),
        DatabaseColumn(
          name: 'status',
          dataType: 'text',
          nullable: false,
          defaultValue: "'NEW'::text",
        ),
      ],
      constraints: const [
        DatabaseConstraint(
          name: 'orders_pkey',
          type: 'PRIMARY KEY',
          definition: 'PRIMARY KEY (id)',
        ),
        DatabaseConstraint(
          name: 'orders_status_check',
          type: 'CHECK',
          definition: "CHECK (status <> ''::text)",
        ),
      ],
      foreignKeys: const [
        DatabaseForeignKey(
          name: 'orders_customer_fk',
          referencedSchema: 'crm',
          referencedTable: 'customers',
          definition:
              'FOREIGN KEY (customer_id) REFERENCES crm.customers(id) ON DELETE RESTRICT',
        ),
      ],
      indexes: const [
        DatabaseIndex(
          name: 'orders_pkey',
          definition:
              'CREATE UNIQUE INDEX orders_pkey ON sales.orders USING btree (id)',
          unique: true,
          primary: true,
          constraintOwned: true,
        ),
        DatabaseIndex(
          name: 'orders_status_idx',
          definition:
              'CREATE INDEX orders_status_idx ON sales.orders USING btree (status)',
        ),
      ],
      triggers: const [
        DatabaseTrigger(
          name: 'orders_audit',
          enabled: 'Enabled',
          definition:
              'CREATE TRIGGER orders_audit AFTER UPDATE ON sales.orders FOR EACH ROW EXECUTE FUNCTION audit_order()',
        ),
      ],
    );

    expect(
      ddl,
      contains('"id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL'),
    );
    expect(ddl, contains('"status" text DEFAULT \'NEW\'::text NOT NULL'));
    expect(ddl, contains('ADD CONSTRAINT "orders_pkey" PRIMARY KEY (id);'));
    expect(ddl, contains('ADD CONSTRAINT "orders_customer_fk" FOREIGN KEY'));
    expect(ddl, contains('CREATE INDEX orders_status_idx'));
    expect(ddl, isNot(contains('CREATE UNIQUE INDEX orders_pkey')));
    expect(ddl, contains('CREATE TRIGGER orders_audit'));
    expect(ddl, contains('ALTER TABLE "sales"."orders" OWNER TO "app_user";'));
    expect(ddl, contains("IS 'Customer''s orders';"));
    expect(ddl, contains('COMMENT ON COLUMN "sales"."orders"."id"'));
  });

  test('view DDL uses the PostgreSQL view definition', () {
    final ddl = PostgresDatabase.buildTableDdl(
      schema: 'reporting',
      table: 'active_users',
      relationType: 'View',
      owner: 'reporter',
      comment: '',
      tablespace: '',
      persistence: 'Permanent',
      viewDefinition: 'SELECT id FROM users WHERE active',
      columns: const [],
      constraints: const [],
      indexes: const [],
      foreignKeys: const [],
      triggers: const [],
    );

    expect(ddl, startsWith('CREATE VIEW "reporting"."active_users" AS'));
    expect(ddl, contains('SELECT id FROM users WHERE active;'));
    expect(ddl, contains('ALTER VIEW "reporting"."active_users" OWNER TO'));
  });

  test('table metadata preserves incoming UML relationships', () {
    const incoming = DatabaseForeignKey(
      name: 'line_items_order_fk',
      sourceSchema: 'sales',
      sourceTable: 'line_items',
      referencedSchema: 'sales',
      referencedTable: 'orders',
      sourceColumns: ['order_id'],
      referencedColumns: ['id'],
      definition: 'FOREIGN KEY (order_id) REFERENCES sales.orders(id)',
    );
    const table = DatabaseTable(
      name: 'orders',
      columns: [],
      ddl: '',
      incomingForeignKeys: [incoming],
    );

    final copied = table.copyWith(owner: 'app_user');
    expect(copied.incomingForeignKeys.single.sourceTable, 'line_items');
    expect(copied.incomingForeignKeys.single.sourceColumns, ['order_id']);
    expect(copied.incomingForeignKeys.single.referencedColumns, ['id']);
  });
}
